import streamlit as st
from datetime import datetime, timedelta
from fpdf import FPDF
from streamlit_drawable_canvas import st_canvas
from PIL import Image
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
import io

# 1. Page Configuration & Theme
st.set_page_config(page_title="Ubuziranenge AI", page_icon="⚖️", layout="centered")

st.markdown("""
    <style>
    .main { background-color: #FFFFFF; }
    h1, h2, h3 { color: #1E3A8A; font-family: 'Arial'; }
    </style>
    """, unsafe_allow_html=True)

# 2. UI HEADER
if os.path.exists("logo.png"):
    st.image("logo.png", width=180)

st.markdown("<h1 style='text-align: center;'>Ubuziranenge AI</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; font-size: 18px;'>Metrology service application assistant</p>", unsafe_allow_html=True)
st.divider()

# 3. CUSTOMER INFORMATION (Added Email Field)
st.subheader("🏢 Customer Information")
col_c1, col_c2 = st.columns(2)
with col_c1:
    company_name = st.text_input("Company Name")
    tin_number = st.text_input("Company TIN Number")
    company_address = st.text_input("Company Address")
with col_c2:
    applicant_name = st.text_input("Name of the Applicant")
    contact_number = st.text_input("Contact Number")
    customer_email = st.text_input("Email Address")

st.divider()

# 4. INSTRUMENT & LOGIC (Condensed for brevity)
lab_mapping = {
    "Legal Metrology Unit": ["Market Scale", "Fuel Pump", "Water Meter", "Electricity Meter", "Taxi Meter", "Weighbridge"],
    "Mass & Balance Lab": ["Analytical Balance", "Industrial Scale", "Standard Weights"],
    "Temperature & Humidity Lab": ["Thermometer", "Oven/Fridge", "Autoclave/Incubator"],
    "Volume & Flow Lab": ["Micropipette", "Laboratory Glassware", "Prover Tank"],
    "Pressure & Force Lab": ["Pressure Gauge", "Compression Machine"],
    "Dimension Lab": ["Vernier Caliper", "Micrometer", "Ruler/Tape Measure"]
}
all_instruments = sorted([item for sublist in lab_mapping.values() for item in sublist])

selected_item = st.selectbox("Select Instrument:", all_instruments)
usage = st.radio("Purpose:", ["Trade/Commercial", "Industrial/Scientific"])
quantity = st.number_input("Number of Instruments:", min_value=1, value=1)

is_trade = "Trade" in usage
if is_trade:
    service_type, lab_assigned, unit_price = "Verification", "Legal Metrology Unit", 500
    total_cost = quantity * unit_price
else:
    service_type, unit_price = "Calibration", 10000
    lab_assigned = next((lab for lab, items in lab_mapping.items() if selected_item in items), "General Lab")
    total_cost = 100000 if quantity >= 10 else quantity * unit_price

collection_date = (datetime.now() + timedelta(days=14)).strftime('%d %B, %Y')

# 5. DIGITAL SIGNATURE
st.subheader("✍️ Digital Signature")
canvas_result = st_canvas(
    stroke_width=2, stroke_color="#000000", background_color="#EEEEEE",
    height=150, drawing_mode="freedraw", key="canvas",
)

# 6. EMAIL & PDF LOGIC
def send_email(pdf_content, recipient_email):
    # NOTE: You must set these in Streamlit "Secrets" for security
    sender_email = "YOUR_GMAIL@gmail.com" 
    password = "sqzh fsom hokk ghhj" 
    
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = f"Metrology Quotation - {company_name}"
    
    body = f"Hello {applicant_name},\n\nPlease find attached your metrology service quotation generated by Ubuziranenge AI."
    msg.attach(MIMEText(body, 'plain'))
    
    part = MIMEBase('application', 'octet-stream')
    part.set_payload(pdf_content)
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f"attachment; filename=RSB_Quotation.pdf")
    msg.attach(part)
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, password)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        st.error(f"Email failed: {e}")
        return False

def create_pdf(sig_image_data):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, "RWANDA STANDARDS BOARD", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", size=10)
    pdf.cell(100, 7, f"Company: {company_name}", ln=True)
    pdf.cell(100, 7, f"TIN: {tin_number}", ln=True)
    pdf.cell(100, 7, f"Instrument: {selected_item} (Qty: {quantity})", ln=True)
    pdf.cell(100, 7, f"Total Cost: {total_cost:,} Rwf", ln=True)
    pdf.cell(100, 7, f"Collection Date: {collection_date}", ln=True)
    
    # Adding the Signature Image to PDF
    if sig_image_data is not None:
        img = Image.fromarray(sig_image_data.astype('uint8'), 'RGBA')
        img.save("temp_sig.png")
        pdf.ln(10)
        pdf.cell(100, 7, "Applicant Signature:", ln=True)
        pdf.image("temp_sig.png", x=10, w=40)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, "Note: This is an automated quotation. Final billing is done at RSB reception.")
    return pdf.output(dest="S").encode("latin-1")

# 7. EXECUTION
if st.button("Confirm & Send Email"):
    if not customer_email:
        st.error("Please provide an email address.")
    else:
        pdf_bytes = create_pdf(canvas_result.image_data)
        if send_email(pdf_bytes, customer_email):
            st.success(f"Quotation sent to {customer_email}!")
        
        st.download_button("Download PDF Manually", data=pdf_bytes, file_name="Quotation.pdf")
